/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:13ac7c41-9f9c-46aa-ab9b-f92398a4ee88",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_T6kgilqz6",
    "aws_user_pools_web_client_id": "mua1r9iubmrosbr8d414loj8d",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER",
        "GENDER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER",
        "GENDER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
